### ISSUE TITLE
check_msa_hardware: new argument - SNMP Port

### ISSUE THREAD

**Issue by sirdemoncze** [david-barbion/monitoring#15]
Hello, can you add "snmp port" as argument for active check behind NAT?

Thank you.

**Comment by david-barbion** [comment]
Hello,

Could you try the fixed version on issue_15 branch?

David

**Comment by sirdemoncze** [comment]
Perfect - it works ;-). Thanks.

**Comment by sirdemoncze** [comment]
Perfect - it works ;-). Thanks.

**Comment by sirdemoncze** [comment]
Perfect - it works ;-). Thanks.
